### ISSUE TITLE
Uncaught TypeError: Object #<Object> has no method 'getComputedStyle' 

### ISSUE THREAD

**Issue by jamieburchell** [RomanMinkin/webkit-span-fix#2]
Hey

When using this plugin in Chrome, with CKeditor 4.2 I'm getting:

Uncaught TypeError: Object #<Object> has no method 'getComputedStyle' 

(anonymous function) plugin.js?t=D6IE:164
arguments.(anonymous function) ckeditor.js:11
i ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire ckeditor.js:12
(anonymous function)

The plugin still seems to work however.

**Comment by RomanMinkin** [comment]
Hi @jamieburchell ,

Try last update https://github.com/RomanMinkin/webkit-span-fix/commit/640efc488627239249cee0a85d7f82eb40ee6448

Should be ok now =)
